# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marzban_manager_pb2 as marzban__manager__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marzban_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarzbanManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/marzban_manager.MarzbanManager/AddUser',
                request_serializer=marzban__manager__pb2.UserCreate.SerializeToString,
                response_deserializer=marzban__manager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/marzban_manager.MarzbanManager/UpdateUser',
                request_serializer=marzban__manager__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=marzban__manager__pb2.UpdateUserReply.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/marzban_manager.MarzbanManager/GetUser',
                request_serializer=marzban__manager__pb2.GetUserRequest.SerializeToString,
                response_deserializer=marzban__manager__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetAllUsers = channel.unary_unary(
                '/marzban_manager.MarzbanManager/GetAllUsers',
                request_serializer=marzban__manager__pb2.GetAllUsersRequest.SerializeToString,
                response_deserializer=marzban__manager__pb2.GetAllUsersReply.FromString,
                _registered_method=True)
        self.GetInbounds = channel.unary_unary(
                '/marzban_manager.MarzbanManager/GetInbounds',
                request_serializer=marzban__manager__pb2.Empty.SerializeToString,
                response_deserializer=marzban__manager__pb2.GetInboundsReply.FromString,
                _registered_method=True)


class MarzbanManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInbounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarzbanManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=marzban__manager__pb2.UserCreate.FromString,
                    response_serializer=marzban__manager__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=marzban__manager__pb2.UpdateUserRequest.FromString,
                    response_serializer=marzban__manager__pb2.UpdateUserReply.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=marzban__manager__pb2.GetUserRequest.FromString,
                    response_serializer=marzban__manager__pb2.UserResponse.SerializeToString,
            ),
            'GetAllUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllUsers,
                    request_deserializer=marzban__manager__pb2.GetAllUsersRequest.FromString,
                    response_serializer=marzban__manager__pb2.GetAllUsersReply.SerializeToString,
            ),
            'GetInbounds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInbounds,
                    request_deserializer=marzban__manager__pb2.Empty.FromString,
                    response_serializer=marzban__manager__pb2.GetInboundsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marzban_manager.MarzbanManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marzban_manager.MarzbanManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarzbanManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marzban_manager.MarzbanManager/AddUser',
            marzban__manager__pb2.UserCreate.SerializeToString,
            marzban__manager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marzban_manager.MarzbanManager/UpdateUser',
            marzban__manager__pb2.UpdateUserRequest.SerializeToString,
            marzban__manager__pb2.UpdateUserReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marzban_manager.MarzbanManager/GetUser',
            marzban__manager__pb2.GetUserRequest.SerializeToString,
            marzban__manager__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marzban_manager.MarzbanManager/GetAllUsers',
            marzban__manager__pb2.GetAllUsersRequest.SerializeToString,
            marzban__manager__pb2.GetAllUsersReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInbounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marzban_manager.MarzbanManager/GetInbounds',
            marzban__manager__pb2.Empty.SerializeToString,
            marzban__manager__pb2.GetInboundsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
